# Generated by Django 5.0.4 on 2024-04-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="author",
            name="born_date",
            field=models.CharField(),
        ),
    ]
